definitions:
  auth_proto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dtos.ResponseDTO:
    properties:
      data: {}
      message:
        type: string
    type: object
  errors.CustomError:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  server.APIKeyResponse:
    properties:
      api_key:
        type: string
      created_at:
        type: string
      message:
        type: string
    type: object
info:
  contact:
    email: ceo@nrmnqdds.com
    name: Quddus
    url: http://www.swagger.io/support
  description: This is the API server for Gomaluum, an API that serves i-Ma'luum data
    for ease of developer.
  license:
    name: Bantown Public License
    url: https://github.com/nrmnqdds/gomaluum-api/blob/main/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Gomaluum API Server
  version: "2.0"
paths:
  /api/ads:
    get:
      description: Get i-Ma'luum ads
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - scraper
  /api/analytics:
    get:
      description: Get analytics summary grouped by level and batch
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - analytics
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Logs in the user. Save the token and use it in the Authorization
        header for future requests.
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - description: Login properties
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth_proto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - auth
  /api/auth/logout:
    get:
      consumes:
      - application/json
      description: Logs out the user. Clears the token from IIUM's CAS. PASETO token
        is still valid.
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - auth
  /api/download/exam-slip:
    get:
      description: Get exam slip PDF from i-Ma'luum
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/pdf
      responses:
        "200":
          description: Exam slip PDF
          schema:
            type: string
      tags:
      - download
  /api/download/study-plan:
    get:
      description: Get study plan PDF from i-Ma'luum
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/pdf
      responses:
        "200":
          description: Exam slip PDF
          schema:
            type: string
      tags:
      - download
  /api/key/generate:
    post:
      consumes:
      - application/json
      description: Generate a new API key for additional authentication layer
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.APIKeyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      summary: Generate API Key
      tags:
      - key
  /api/profile:
    get:
      description: Get i-Ma'luum profile
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - scraper
  /api/result:
    get:
      description: Get result from i-Ma'luum
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - scraper
  /api/schedule:
    get:
      description: Get schedule from i-Ma'luum
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - scraper
  /api/starpoint:
    get:
      description: Get co-curricular from i-Ma'luum
      parameters:
      - description: API key for additional security layer
        in: header
        name: x-gomaluum-key
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDTO'
      tags:
      - scraper
  /health:
    get:
      description: Check the health of the application.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - misc
swagger: "2.0"
